kind: workflow
description: some workflow 2
scope: env_resource
label-selector: vm

inputs:
    vm_prefix:
        type: String
        default: 'data_'
    koko:
        type: String

jobs:
    filter_vms:
        kind: shell
        spec:
            agent:
                name: test_agent
            sources:
                - store: tomer_playground
                  path: scripts/filter_vms.sh
            commands:
                - './filter_vms env_id={{ .bindings.environment_id }} vm_prefix={{ .inputs.vm_prefix }}'
            outputs:
                - vm_list

    take_vms_snapshots:
        kind: shell
        depends-on: filter_vms
        spec:
            items: '{{ .jobs.filter_vms.outputs.vm_list }}'
            agent:
                name: test_agent
            sources:
                - store: tomer_playground
                  path: scripts/take_snapshot.sh
            commands:
                - 'echo running take_snapshot on vm {{ .item }}'
                - './take_snapshot.sh vm={{ .item }}'

    print_snapshots_paths:
        kind: shell
        depends-on: take_vms_snapshots
        spec:
            agent:
                name: test_agent
            commands:
                - 'echo Message from param: {{ .bindings.resource_id }}'
                - 'echo the snapshots are ready: {{ .jobs.take_vms_snapshots.result }}'